### ISSUE TITLE
meme text looks bad in ubuntu

### ISSUE THREAD

**Issue by Fresheyeball** [adriancooney/console.image#6]
It just does!

**Comment by adriancooney** [comment]
![Oh no!](http://i.imgur.com/OqXob.gif)

I'm not really sure there's much I can do, all the text rendering is done with `fillText` and `strokeText` on the canvas.

**Comment by Fresheyeball** [comment]
I believe its the "Impact" font not being available on all platforms: https://github.com/dunxrion/console.image/blob/master/console.image.js#L69 

Give me a bit and I will research an answer.

**Comment by Fresheyeball** [comment]
Ok, so it is a font issue, but there is an easy work around for us ubuntu users. There is a package `ttf-mscorefonts-installer` in the ubuntu software center that give linux the impact font. Would you mind just adding that to your documentation?

**Comment by adriancooney** [comment]
Thanks for the detective work! Will do.

**Comment by Fresheyeball** [comment]
I am shamelessly re-using this thread to inform you that I have OSed my personal logging class which makes use of your library. https://github.com/Fresheyeball/Clog Just to show some ways its being used.
